modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="hexalia"
version="${mod_version}"
displayName="Hexalia"
displayURL="https://github.com/AstralyaStudios/Hexalia"
authors="Astralya Studios"

description='''Hexalia is a folk-witchcraft Minecraft mod centered on nature, cultivation, herbal practices, rituals, environmental magic, and handcrafted magical tools.'''

[[dependencies.hexalia]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexalia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexalia]]
    modId="geckolib"
    mandatory=true
    versionRange="${geckolib_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexalia]]
    modId="patchouli"
    mandatory=false
    versionRange="${patchouli_version_range}"
    ordering="NONE"
    side="BOTH"
